version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - contentful
  - dotenvx
  - ianvs
  - lcov
  - lucide
  - mahato
  - mantine
  - nprogress
  - pino
  - piyush
  - weightage
import: []
