name: main

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 2:00 AM IST
    - cron: '0 20 * * *'

jobs:
  track-web-vitals:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Load Environment Variables
        run: |
          touch .env.production
          echo DATABASE_URL=${{secrets.DATABASE_URL}} >> .env.production

      - name: Install Dependencies
        run: pnpm install

      - name: Generate Prisma Types
        run: pnpm generate

      - name: Run Script
        run: pnpm start
