name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Run Automation App Tests
        uses: ./.github/worflows/tests/test-automation-app.yaml
