name: test-automation-app

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  run-automation-app-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm type-check

      - name: Run Tests
        run: pnpm test

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/automation/coverage

      - name: Copy coverage folder to root
        run: cp -r apps/automation/coverage .

      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main
